// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptContent(arg1, arg2) {
  return window['go']['main']['App']['DecryptContent'](arg1, arg2);
}

export function EncryptContent(arg1, arg2) {
  return window['go']['main']['App']['EncryptContent'](arg1, arg2);
}
