// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptContent(arg1:string,arg2:string):Promise<string>;

export function EncryptContent(arg1:string,arg2:string):Promise<string>;
